/*
 * Copyright 2026 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.securitiestransferchargesaveandreturn.models

import play.api.libs.json.{Format, Json, Reads, Writes}
import play.api.mvc.PathBindable
/*
 * Submission Ids are generated by the STC save and return service.
 * They are used as unique Ids for user drafts and submissions.
 */
final case class SubmissionId(value: String) extends AnyVal {
  override def toString: String = value
}

object SubmissionId {
  implicit def pathBindable(implicit strBinder: PathBindable[String]): PathBindable[SubmissionId] =
    new PathBindable[SubmissionId] {

      override def bind(key: String, value: String): Either[String, SubmissionId] =
        strBinder.bind(key, value).map(SubmissionId.apply)

      override def unbind(key: String, submissionId: SubmissionId): String =
        strBinder.unbind(key, submissionId.value)
    }

  implicit val format: Format[SubmissionId] =
    Json.valueFormat[SubmissionId]

}